### ISSUE TITLE
Error while reading precomp directory contents

### ISSUE THREAD

**Issue by jjatria** [atroxaper/raku-RaCoCo#10]
Thank you for your work on racoco! I've been waiting for a tool like this one for a while now. :dagger: 

I tried recently to run it as part of my CI setup, but I ran into a strange error that I cannot actually reproduce locally. You can see the error in question on the logs for that job here: https://gitlab.com/jjatria/raku-game-entities/-/jobs/1735233677, but the relevant part is

```
$ racoco --exec='prove6 -Ilib' --html --fix-compunit
Failed to get the directory contents of '/builds/jjatria/raku-game-entities/lib/.precomp': Failed to open dir: No such file or directory
  in sub MAIN at /usr/share/perl6/site/sources/44A4D1B35D8BDF9C08695E7730B9BD23D1D0C3D6 (App::Racoco::Cli) line 122
  in block <unit> at /usr/share/perl6/site/resources/1737D3959927C9BF0C4E4A1C2EA9DB935C657379 line 2
  in sub MAIN at /usr/share/perl6/site/bin/racoco line 3
  in block <unit> at /usr/share/perl6/site/bin/racoco line 1
```

Any idea what might be the reason?

**Comment by atroxaper** [comment]
@jjatria Thank you for the report. Yes, I've faced such behavior. It happens when we run racoco on a library without .precomp directory at all. I've fixed it in v.1.4.5 (released a minute ago). Please try it now.
