### ISSUE TITLE
RaCoCo + App::mi6 bug?

### ISSUE THREAD

**Issue by melezhik** [atroxaper/raku-RaCoCo#12]
Hi @atroxaper ! I found this while playing with SparkyCI:

* `racoco -l html` fails for App::Mi6 - http://sparrowhub.io:2222/report/336
* The same build without rakcoco succeeds `zef test .`. - http://sparrowhub.io:2222/report/335

HTH

Aleksei

**Comment by melezhik** [comment]
cc @skaji

**Comment by atroxaper** [comment]
@melezhik Hello! Thank you for your report. Finally I found a time to fix it in v1.6.0 (just released). The issue was in `no precompilation` pragma in one of modules of App::Mi6.
