### ISSUE TITLE
Make output file variable

### ISSUE THREAD

**Issue by JJ** [atroxaper/raku-RaCoCo#17]
The directory where we're testing need not be writable; that's usually the case in JJ/alpine-raku#28
It would help if an environment variable would say where we're storing `coverage.log` and/or the directory where `.racoco`  is being created.

**Comment by atroxaper** [comment]
Hello @JJ 

I agree. There are specific cases when we do not what to create `.racoco` directory in the project directory. I will going to implement it. It requires a reviewing all my IO::Path related code. Fortunately, I group up the code together initially. I also have a task about some improvements in that code. And, of course it requires a bunch of adequate tests.

Thank you!

**Comment by atroxaper** [comment]
Hello @JJ 

I implemented the feature in App::RaCoCo:ver<2.0.1>. Now you could pass something like `--cache-dir=/home/jj/.racoco-cache` in racoco command line. Or use any possible ways to pass `cache-dir` option to racoco.

**Comment by JJ** [comment]
brilliant! Thanks!
