### ISSUE TITLE
Error after successfully run tests

### ISSUE THREAD

**Issue by wbiker** [atroxaper/raku-RaCoCo#3]
Running all tests with `RAKULIB=/home/wolf/repos/module2rpm racoco` 
showing an error:
```raku
All tests successful.
Files=10, Tests=82,  10 wallclock secs
Result: PASS
===SORRY!===
Library path ｢/home/wolf/repos/module2rpm/lib/.precomp｣ has ambiguous .precomp folder with more than one CompUnit Repository
```
Removing the ./lib/.precomp folder helped.

**Comment by atroxaper** [comment]
@wbiker Hello. Thank you for your interest in RaCoCo. 

RaCoCo needs to analyze compiled source code to understand which lines of code can be executed. Each compiler version makes a separate folder under `.precomp` folder. As a user may run tests by any command, RaCoCo can’t guess which folder it must analyze. That is why the error may be displayed. Probably, you run your test under several compiler versions. Your decision to clean `.precomp` folder was the correct fix. 

I’m going to add Frequently Problems sections in the readme and add the corresponding action points to a user about cleaning `.precomp` folder.

**Comment by wbiker** [comment]
I see, that makes sense.
Is there a way to find the most recent one? Maybe by using the youngest one?
Anyways. thanks for explanation

**Comment by atroxaper** [comment]
@wbiker, it is not about the youngest one. A user may run tests with the old compiler version for purpose, and compiled files may not change. Probably, I need to add a kind of `--force` option for cleaning `.precomp` folder before tests run.

**Comment by wbiker** [comment]
You are right.
I wonder, if its ok to just remove the .precomp folders by default. Probably not^^

Anyways. Thanks for this module and the work you put into.
