### ISSUE TITLE
Allow for pluggable reporters

### ISSUE THREAD

**Issue by jjatria** [atroxaper/raku-RaCoCo#9]
In the Perl world, the `cover` command provided by App::Cover can be called like `cover -report Foo` which will use `Devel::Cover::Report::Foo` to handle the report. This allows other people to develop their own reporters, which can be used without changing the core tool.

`racoco` has App::RaCoCo::Report::ReporterHTML to handle the HTML report, but maybe we could have a similar mechanic here? That way, we could write eg. an App::RaCoCo::Report::Coveralls that does not need to be shipped with racoco, but that could be used with something like `racoco --report=Coveralls` to send data to that service.

What do you think?

**Comment by jjatria** [comment]
Ah, this is mentioned in the Roadmap, I notice. Is there any way I could help? :D

**Comment by atroxaper** [comment]
@jjatria Hello! Thank you for your interest in RaCoCo. Yes, I'm going to do some pluggable mechanism. For now I'm not sure with which exactly information (or on which stage) the plugin should be called. Thanks for link me to Perl's `cover`, I will look closer to it.

Also, for now you can parse `.racoco/report.txt` file and convert it for your purpose. Format is:
<overall-coverage-level>%
<
<file-name>
<file-coverage-level>%
<green <covered-lines-numbers>>
<red <not-covered-lines-numbers>>
<purple <not-coverable-but-covered-lines-numbers-it-is-possible-strange-compiler-behaviour>
>+

**Comment by atroxaper** [comment]
@jjatria Hello. Only for you (joke) I've just released RaCoCo v1.5.0 and [App::Racoco::Report::ReporterCoveralls](https://raku.land/zef:atroxaper/App::Racoco::Report::ReporterCoveralls) reporter. Enjoy! :)
